[env]
# Aqui você pode definir variáveis de ambiente, se precisar depois

[tasks.build]
description = "Compila o serviço principal (Kotlin) e o microsserviço (Go)"
run = """
#!/bin/bash
echo "Compilando o Kotlin/Ktor..."
cd api-ktor && ./gradlew build -x test

echo "Compilando o Go..."
# Descomente e ajuste a linha abaixo quando criar a pasta do Go
# cd api && go build -o bin/app
echo "Build concluído!"
"""

[tasks.test]
description = "Roda a suíte de testes de todos os projetos"
run = """
#!/bin/bash
echo "Rodando testes do Kotlin/Ktor..."
cd api-ktor && ./gradlew test

echo "Rodando testes do Go..."
# Descomente e ajuste a linha abaixo quando criar a pasta do Go
# cd api && go test ./...
echo "Testes concluídos!"
"""